Slumbus/front-end

src/navigation/ChildrenListStack.tsx

design: 아이 목록 네이게이트 이름 및 폰트 적용

---

src/components/BottomPlayer.tsx
src/screens/HomeScreen.tsx

feat: 하단 재생바 ui 구현

---

package-lock.json
package.json
src/screens/composition/HummingScreen.tsx
yarn.lock

feat: 허밍 선택 화면 음악 재생

---

App.tsx
index.js
package-lock.json
package.json
service.js
src/components/play/PlayButtonBarContainer.tsx
src/screens/HomeScreen.tsx
src/screens/play/PlayController.tsx
src/screens/play/PlayScreen.tsx
yarn.lock

feat: 재생화면-음악 트랙 재생 기능

---

src/screens/children/ChildrenListScreen.tsx

1. 아이 목록에서 앨범 이미지 좌우 스크롤 안되던 문제 해결
2. 스크롤 숨김 처리

fix: 아이 목록 이미지 스크롤 수정

---

android/app/src/main/AndroidManifest.xml
src/components/BottomPlayer.tsx
src/components/play/MusicItem.tsx
src/components/play/PlayButtonBarContainer.tsx
src/contexts/PlaybackContext.tsx
src/navigation/HomeStack.tsx
src/screens/HomeScreen.tsx
src/screens/play/PlayController.tsx
src/screens/play/PlayScreen.tsx

- 이전 곡 & 다음 곡 재생
<문제 상황>
- 첫번째 곡에서 이전 곡 (예외처리 필요 - 현재 오류 발생)
- 마지막 곡에서 다음 곡 (예외처리 필요 - 현재 오류 발생)
- 재생 버튼 동작 상태 관리 개선 필요

feat: 이전 곡 / 다음 곡 재생

---

src/components/play/PlayButtonBarContainer.tsx
src/screens/HomeScreen.tsx
src/screens/auth/LoginScreen.tsx
src/screens/play/PlayScreen.tsx

- 마지막 곡에서 다음 곡 하면 첫번재 곡으로 재생하는 예외처리 추가
- 첫번째 곡에서 이전 곡 하면 마지막 곡으로 재생하는 예외처리 추가
- 다른 앨범 재생시 첫번째 곡으로만 재생되는 오류 수정

feat: 이전 곡 / 다음 곡 예외처리 추가

---

src/navigation/HomeStack.tsx
src/navigation/MainNavigator.tsx
src/screens/MyScreen.tsx
src/screens/mypage/EditPWScreen.tsx
src/screens/mypage/EditProfileScreen.tsx

- 마이페이지 화면
- 프로필 수정 화면
- 비밀번호 수정 화면

feat: 마이페이지 화면, 프로필 수정 화면, 비밀번호 수정 화면

---

src/screens/MyScreen.tsx
src/screens/mypage/EditPWScreen.tsx
src/screens/mypage/EditProfileScreen.tsx

fix: 마이페이지 수정

---

package-lock.json
package.json
src/screens/composition/HummingScreen.tsx
yarn.lock

- 오류 없이 구동되나 녹음한 음성이 안 들리는 이슈 존재.
- 환경 문제일 경우를 상정하여 병합.

feat: 허밍 선택 화면 녹음 기능 구현

---

src/components/button/RepeatButton.tsx
src/components/play/PlayButtonBarContainer.tsx
src/screens/HomeScreen.tsx
src/screens/play/PlayScreen.tsx

- 자동으로 넘어가는 음악에 대한 화면 전환 이벤트
- 앨범 전체 반복 설정
- 한곡 반복 설정
- (추후 구현) 한곡 재생 후 종료

feat: 반복모드 설정

---

src/components/BottomPlayer.tsx
src/screens/HomeScreen.tsx

feat: 하단 플레이어 다음곡 / 이전곡

---

src/components/play/MusicItem.tsx
src/components/play/PlayButtonBarContainer.tsx
src/navigation/HomeStack.tsx
src/screens/play/LyricsScreen.tsx
src/screens/play/PlayScreen.tsx
src/screens/play/PlaylistScreen.tsx

- 재생 전환 시 재생 화면으로 이동
- 순서 편집 시 새로고침되어 트랙 1번 재생 오류
- 재생 화면에서 큐를 전달 받기 떄문에 다시 재생 목록으로 들어가면 이전 큐로 보이는 오류

feat: 재생 목록 재생 전환 및 순서 편집

---

src/screens/HomeScreen.tsx

- 재생화면 진입 시 0번 트랙 화면 노출 되는 문제 해결

fix: 인덱스 0번 트랙 재생화면 노출 해결

---

src/screens/play/PlayScreen.tsx

- 타이머 기능 구현
- 타이머 남은 시간 실시간 표시

feat: 취침 타이머 기능

---

package-lock.json
package.json
src/components/AlbumTitleText.tsx
src/screens/HomeScreen.tsx
yarn.lock

- 홈 화면 api 연결
- 엔티티 수정 후 반영 필요
- 로그인 기능 구현 후 토큰 전달부 구현

feat: 홈 화면 api 연결

---

src/components/modal/AlbumPhotoSelectModal.tsx
src/components/modal/MusicSaveModal.tsx
src/screens/composition/ChildSelectScreen.tsx
src/screens/composition/MelodySaveScreen.tsx

- 아이 선택 화면  api 연결
- 저장가 저장 화면 api 연결 시도 (음악 파일 문제인 듯하여 우선 병합)

feat: 작곡 화면 api 연결

---

src/screens/children/ChildrenInfoPlaylistScreen.tsx
src/screens/children/ChildrenInfoReactionScreen.tsx
src/screens/children/ChildrenListScreen.tsx

feat: 자장가 반응 목록 api 연동

---

src/screens/composition/HummingScreen.tsx
src/screens/composition/MelodySaveScreen.tsx
src/screens/composition/MoodSelectScreen.tsx

- 자장가 작곡 스크린 자장가 확인 재생 추가
- 분위기, 악기 데이터 로그로 표시(해당 데이터 백엔드로 전송)

feat: 작곡된 자장가 멜로디 재생

---

src/screens/composition/HummingScreen.tsx
src/screens/composition/MoodSelectScreen.tsx

- 생성된 음악 데이터 구조 수정
- 분위기/악기 2개 이상 선택시 토스트 메시지
- 허밍 테스트 파일 전달되도록 수정

fix: 생성된 음악 데이터 구조 수정

---

src/components/BottomPlayer.tsx
src/navigation/MainNavigator.tsx
src/screens/HomeScreen.tsx
src/screens/composition/HummingScreen.tsx
src/screens/play/PlayScreen.tsx

- 재생화면 -> 자장가 반응 작성 이동 구현
- 홈 화면 하단 재생 탭 오류 수정
- 허밍 더미데이터 전달부 삭제

fix: 홈 화면, 허밍 파일 오류 수정

---

src/screens/play/PlayScreen.tsx

feat: 타이머 시간 종료 후  음악 정지

---

src/screens/composition/MoodSelectScreen.tsx

feat: 자장가 분위기 입력값 영어 매핑

---

src/screens/composition/MoodSelectScreen.tsx

feat: 분위기 입력값 수정

---

src/components/modal/AlbumPhotoSelectModal.tsx
src/components/modal/FileSelectModal.tsx
src/components/modal/LyricsSaveModal.tsx
src/components/modal/MusicSaveModal.tsx
src/screens/HomeScreen.tsx
src/screens/children/ChildrenInfoPlaylistScreen.tsx
src/screens/children/ChildrenListScreen.tsx
src/screens/composition/ChildSelectScreen.tsx
src/screens/composition/HummingScreen.tsx
src/screens/lyrics/SelectLyricWritingListScreen.tsx

- 등록된 데이터(아이, 자장가, 반응) 없을 시 안내 문구 추가
- 모달 취소 아이콘 변경

refactor: 등록된 데이터 없을 경우 처리 및 모달 아이콘 변경

---

src/screens/children/ChildrenInfoPlaylistScreen.tsx
src/screens/children/ChildrenInfoReactionRegisterScreen.tsx

아이 목록에서 자장가 반응 등록 시, 등록된 데이터를 반영하여 화면 업데이트

fix: 자장가 반응 등록 후 아이목록에서 데이터 갱신

---

src/screens/composition/MoodSelectScreen.tsx

[feat] 소제목 수정

---

src/screens/SongCompletionScreen.tsx
src/screens/SongCompletionScreen2.tsx
src/screens/lyrics/LyricsRecordingScreen.tsx
src/screens/lyrics/LyricsWritingScreen.tsx

- 생성 음악 확인용 사운드 라이브러리 해당 화면 벗어나면 재생 멈추도록 설정

feat: 페이지 벗어나면 사운드 라이브러리  재생 정지

---

package-lock.json
src/components/LyricSong.tsx
src/screens/lyrics/SelectLyricWritingListScreen.tsx

feat: 작사 버튼 비활성화
